### ISSUE TITLE
Netopeer2 Listening on V4. Should be v6.

### ISSUE THREAD

**Issue by iffy50** [sartura/feed-openwrt-terastream-v1.x.x#1]
Netopeer2 is starting up only listening on IPv4 (0.0.0.0). For Terastream, this needs to startup listening on (::) so that it is usable on deployment. 

I can make the change manually to the netconf-server module to listen on v6, but this needs to be fixed in the feed as the default for terastream client.

**Comment by jpetrina** [comment]
Thanks, this has been resolved in https://github.com/sartura/openwrt-feed-sysrepo/commit/7b53019e67c9d5e23a67233b7a7c79f160219280.

**Comment by jpetrina** [comment]
This is currently being upstreamed at https://github.com/openwrt/packages/pull/14515.

**Comment by jsmolic** [comment]
This has been resolved in https://github.com/sartura/openwrt-feed-sysrepo
